public class Calculater {
    public void add(Integer num1, Integer num2){
        System.debug('Show the Result' + (num1 + num2));
    }
    public void sub(Integer num1, Integer num2){
        System.debug('Show the Result' + (num1 - num2));
    }
    public void mil(Integer num1, Integer num2){
        System.debug('Show the Result' + (num1 * num2));
    }
    public void div(Integer num1, Integer num2){
        System.debug('Show the Result' + (num1 / num2));
    }
        public String firstName = 'Akbar';
        public String lastName = 'Ali';
        public Boolean isActive = true;
        public Decimal point = 2.2;
        public Integer num = 10;
}



