public class PracticeallClass {

}

String day = 'Tuesday';

switch on day {
    when 'Monday' {
        System.debug('Start of the work week!');
    }
    when 'Tuesday' {
        System.debug('Start break time enjoy time');
    }
    when 'Wednesday' {
        System.debug('Reading time enjao reading');
    }
    when 'Thusday' {
        System.debug('Parents Miting day');
    }
    when 'Friday' {
        System.debug('Weekend is almost here!');
    }
    when 'Sataday' {
        System.debug('Time to relex day');
    }
    when 'Sunday' {
        System.debug('Time to relax!');
    }
    when else {
        System.debug('It\'s just another day.');
    }
}




//  Integer a = 20;
//  a+=5;
//  if(a > 5 )
//  {
//     System.debug('Number = ' + a);
//  }
// else{
// System.debug('Number is Not 10');

// }
 